name: notsohip
favicon: null
layout_spectrum: 0.9877394910436124
typography_spectrum: 0.9390667404513806
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4585669955704361
  lightness: 0.04338592803105712
  saturation: 0.28086026920937
  rhythmicContrast: 0.79642154998146
purpose: []
